package com.fitness.Constant;

public enum Fragment {
    GENERAL,
    WITH_CARD,
    WITHOUT_CARD,
    CUSTOMER,
    EDIT_CUSTOMER,
    ADD_CUSTOMER,
    EMPLOYEE,
    EDIT_EMPLOYEE,
    ADD_EMPLOYEE,
    EMPLOYMENT,
    POSITION,
    SUBSCRIPTION,
    EDIT_SUBSCRIPTION,
    ADD_SUBSCRIPTION,
    REPORT,
    SETTINGS;
}
